use std::sync::Arc;

use anyhow::Result;
use tokio_cron_scheduler::{Job, JobScheduler};
use tracing::{error, info};

use crate::config::{CronConfig, GitHubConfig};
use crate::tools::github::GitHubClient;

/// Shared context for cron jobs.
pub struct CronContext {
    pub github: Option<GitHubClient>,
    pub github_config: GitHubConfig,
    pub cron_config: CronConfig,
    /// Discord HTTP client for sending notifications.
    pub discord_http: Option<Arc<serenity::http::Http>>,
}

/// Start the cron scheduler.
pub async fn start(ctx: Arc<CronContext>) -> Result<()> {
    let sched = JobScheduler::new().await?;

    // GitHub scan job
    if let Some(ref _gh) = ctx.github {
        let cron_expr = &ctx.cron_config.github_scan;
        let ctx_clone = Arc::clone(&ctx);

        let job = Job::new_async(cron_expr.as_str(), move |_uuid, _lock| {
            let ctx = Arc::clone(&ctx_clone);
            Box::pin(async move {
                run_github_scan(&ctx).await;
            })
        })?;

        sched.add(job).await?;
        info!(schedule = %cron_expr, "Scheduled github_scan cron job");
    }

    sched.start().await?;

    // Keep scheduler alive — caller is responsible for keeping the task alive.
    // We just loop and sleep rather than using tokio::signal (avoids extra feature).
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(3600)).await;
    }
}

/// Execute a GitHub scan and optionally notify Discord.
pub async fn run_github_scan(ctx: &CronContext) {
    let github = match &ctx.github {
        Some(gh) => gh,
        None => {
            error!("GitHub client not configured");
            return;
        }
    };

    info!("Running GitHub scan");

    let mut results = Vec::new();
    for repo in &ctx.github_config.repos {
        match github.scan_repo(repo).await {
            Ok(result) => results.push(result),
            Err(e) => error!(%repo, %e, "Failed to scan repo"),
        }
    }

    let report = GitHubClient::format_scan_report(&results);
    info!("\n{report}");

    // Send to Discord if configured
    if let (Some(http), Some(channel_id)) = (
        &ctx.discord_http,
        ctx.github_config.notify_discord_channel_id(),
    ) {
        if let Err(e) = serenity::model::id::ChannelId::new(channel_id)
            .say(http.as_ref(), &truncate(&report, 2000))
            .await
        {
            error!(%e, "Failed to send scan report to Discord");
        }
    }
}

/// Execute auto-PR for a specific issue.
pub async fn run_auto_pr(
    ctx: &CronContext,
    runner: &crate::agent::AgentRunner,
    repo: &str,
    issue_number: u64,
) -> Result<String> {
    let github = ctx
        .github
        .as_ref()
        .context("GitHub client not configured")?;

    // 1. Fetch the issue
    let issue = github.get_issue(repo, issue_number).await?;
    let issue_title = &issue.title;
    let issue_body = issue.body.as_deref().unwrap_or("(no description)");

    info!(%repo, issue_number, %issue_title, "Starting auto-PR");

    // 2. Ask LLM to analyze and generate a fix
    let prompt = format!(
        "You are a senior developer. Analyze this GitHub issue and generate a fix.\n\n\
         Repository: {repo}\n\
         Issue #{issue_number}: {issue_title}\n\
         Description:\n{issue_body}\n\n\
         Respond with EXACTLY this format:\n\
         FILE: <path>\n\
         ```\n<file content>\n```\n\
         COMMIT_MESSAGE: <message>\n\n\
         Only modify one file. Keep the change minimal."
    );

    let response = runner.run_streaming(&prompt, &[], |_| {}).await?;

    // 3. Parse the LLM response
    let (file_path, file_content, commit_msg) = parse_fix_response(&response)?;

    // 4. Create branch
    let branch_name = format!("rustclaw/fix-issue-{issue_number}");
    github
        .create_branch(repo, &branch_name, "main")
        .await?;

    // 5. Commit the fix
    github
        .commit_file(repo, &file_path, &file_content, &commit_msg, &branch_name)
        .await?;

    // 6. Create PR
    let pr_body = format!(
        "Fixes #{issue_number}\n\n\
         Auto-generated by rustclaw.\n\n\
         ## Changes\n{commit_msg}"
    );
    let pr_url = github
        .create_pr(
            repo,
            &format!("fix: {issue_title}"),
            &pr_body,
            &branch_name,
            "main",
        )
        .await?;

    Ok(pr_url)
}

/// Parse the LLM's fix response into (file_path, content, commit_message).
fn parse_fix_response(response: &str) -> Result<(String, String, String)> {
    let file_path = response
        .lines()
        .find(|l| l.starts_with("FILE:"))
        .map(|l| l.trim_start_matches("FILE:").trim().to_string())
        .context("LLM response missing FILE: line")?;

    // Extract code block
    let content = if let Some(start) = response.find("```") {
        let after_start = &response[start + 3..];
        // Skip optional language tag on same line
        let code_start = after_start.find('\n').unwrap_or(0) + 1;
        let after_lang = &after_start[code_start..];
        if let Some(end) = after_lang.find("```") {
            after_lang[..end].to_string()
        } else {
            after_lang.to_string()
        }
    } else {
        anyhow::bail!("LLM response missing code block");
    };

    let commit_msg = response
        .lines()
        .find(|l| l.starts_with("COMMIT_MESSAGE:"))
        .map(|l| l.trim_start_matches("COMMIT_MESSAGE:").trim().to_string())
        .unwrap_or_else(|| "fix: address issue (auto-generated)".to_string());

    Ok((file_path, content, commit_msg))
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}...(truncated)", &s[..max - 15])
    }
}

use anyhow::Context;
